version: '3.2'
services:
  proxy:
    image: nginx:alpine
    ports:
      - '8989:8989'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - uwsgi
    networks:
      - 'cadccutout'

  uwsgi:
    image: opencadc/cadccutout-server-uwsgi:3.7-alpine
    build:
      context: uwsgi
    volumes:
      - './uwsgi/main.py:/usr/src/uwgi-app/main.py'
      - '/Users/jenkinsd/Data/cutouts:/usr/src/data:ro'
    networks:
      - 'cadccutout'

networks:
  cadccutout:
